from typing import Type, Any

class PydanticOutputParser:
    def __init__(self, pydantic_object: Type[Any]) -> None: ...
    def get_format_instructions(self) -> str: ...
    def parse(self, text: str) -> Any: ...
