from typing import Any

class Canvas:
    def __init__(self, filename: str, pagesize: Any = ...) -> None: ...
    def save(self) -> None: ...

def canvas(filename: str, pagesize: Any = ...) -> Canvas: ...
