from typing import Any

class Page:
    def get_text(self) -> str: ...


class Document:
    def __init__(self, stream: Any = ...) -> None: ...
    def load_page(self, n: int) -> Page: ...
    def __len__(self) -> int: ...


def open(stream: Any = ...) -> Document: ...
