/**
 * Demo data for development and fallback mode
 * Used when API is unavailable or in demo mode
 */

import type { ValidationResults } from "./types"

export const demoResults: ValidationResults = {
  document_id: "demo-123",
  filename: "Q4_2024_Investment_Report.pptx",
  overall_status: "error",
  compliance_score: 67,
  total_issues: 14,
  issues_by_severity: {
    error: 0,
    warning: 0,
    critical: 2,
    high: 5,
    medium: 4,
    low: 3,
  },
  category_counts: {
    esg: {
      total: 2,
      critical: 1,
      high: 1,
      medium: 0,
      low: 0,
    },
    performance: {
      total: 5,
      critical: 1,
      high: 2,
      medium: 1,
      low: 1,
    },
    disclaimers: {
      total: 4,
      critical: 0,
      high: 2,
      medium: 2,
      low: 0,
    },
    registration: {
      total: 3,
      critical: 0,
      high: 0,
      medium: 1,
      low: 2,
    },
  },
  compliance_issues: [],
  issues_by_category: {
    esg: [
      {
        issue_type: "esg_overmentioned_article8",
        severity: "critical",
        category: "esg",
        location: "Slides 3, 5, 7",
        slide_number: 3,
        message: "Article 8 fund exceeds 10% ESG text limit (15.3% found)",
        context:
          "Total ESG content across document: 4821 characters representing 15.3% of total document content, exceeding the regulatory limit of 10%.",
        suggestion: "Reduce ESG-related content to below 10% of total document text",
        auto_fixable: false,
        rule_reference: "Section 4.1 - ESG Compliance Guidelines",
      },
      {
        issue_type: "missing_sfdr_disclosure",
        severity: "high",
        category: "esg",
        location: "Slide 2",
        slide_number: 2,
        message: "Missing SFDR Article 8 principal adverse impacts disclosure",
        suggestion: "Add required SFDR disclosure statement",
        auto_fixable: true,
        rule_reference: "SFDR Article 8 Requirements",
      },
    ],
    performance: [
      {
        issue_type: "benchmark_mismatch",
        severity: "high",
        category: "performance",
        location: "Slide 12",
        slide_number: 12,
        message: "Benchmark comparison uses incorrect index (MSCI World vs stated S&P 500)",
        context:
          "Performance chart shows comparison to MSCI World Index but fund documents specify S&P 500 as benchmark.",
        suggestion: "Update benchmark comparison to use S&P 500 Index",
        auto_fixable: false,
        rule_reference: "Section 2.3 - Performance Presentation Standards",
      },
      {
        issue_type: "missing_time_period",
        severity: "medium",
        category: "performance",
        location: "Slide 8",
        slide_number: 8,
        message: "Performance table missing required time period labels",
        suggestion: "Add YTD, 1Y, 3Y, 5Y column headers",
        auto_fixable: true,
        rule_reference: "Section 2.1 - Required Performance Periods",
      },
    ],
    structure: [
      {
        issue_type: "logo_placement",
        severity: "low",
        category: "structure",
        location: "Slides 1, 15",
        slide_number: 1,
        message: "Company logo not in standard position (top-right corner)",
        suggestion: "Move logo to top-right corner per brand guidelines",
        auto_fixable: true,
        rule_reference: "Brand Guidelines v2.1",
      },
    ],
    disclaimers: [
      {
        issue_type: "outdated_disclaimer",
        severity: "high",
        category: "disclaimers",
        location: "Slide 20",
        slide_number: 20,
        message: "Legal disclaimer references outdated regulatory framework (pre-2024)",
        context: 'Current disclaimer text: "In accordance with MiFID II regulations as of January 2023..."',
        suggestion: "Update disclaimer to reflect current 2024 regulatory requirements",
        auto_fixable: true,
        rule_reference: "Legal Compliance - Disclaimer Standards",
      },
      {
        issue_type: "missing_risk_warning",
        severity: "critical",
        category: "disclaimers",
        location: "Slides 1-5",
        slide_number: 1,
        message: "Opening slides missing required risk warning for retail investors",
        suggestion: "Add standard risk warning statement to introduction slides",
        auto_fixable: true,
        rule_reference: "PRIIPS KID Requirements",
      },
    ],
    data_consistency: [
      {
        issue_type: "nav_mismatch",
        severity: "high",
        category: "data_consistency",
        location: "Slides 6, 14",
        slide_number: 6,
        message: "NAV values inconsistent between slides (€142.50 vs €142.35)",
        context: "Slide 6 shows NAV as €142.50, Slide 14 shows €142.35",
        suggestion: "Verify correct NAV and update all references",
        auto_fixable: false,
        rule_reference: "Data Accuracy Standards",
      },
      {
        issue_type: "date_inconsistency",
        severity: "medium",
        category: "data_consistency",
        location: "Slides 4, 9",
        slide_number: 4,
        message: 'Different "as of" dates used for same reporting period',
        suggestion: "Standardize to single reporting date across all slides",
        auto_fixable: false,
        rule_reference: "Reporting Consistency Guidelines",
      },
    ],
    other: [
      {
        issue_type: "font_inconsistency",
        severity: "low",
        category: "other",
        location: "Slides 7, 11, 13",
        slide_number: 7,
        message: "Multiple font families detected (Arial, Calibri mixed usage)",
        suggestion: "Standardize to approved font family (Arial)",
        auto_fixable: true,
        rule_reference: "Brand Guidelines - Typography",
      },
      {
        issue_type: "image_resolution",
        severity: "low",
        category: "other",
        location: "Slide 10",
        slide_number: 10,
        message: "Chart image below recommended resolution (72dpi vs 150dpi minimum)",
        suggestion: "Replace with higher resolution image",
        auto_fixable: false,
        rule_reference: "Quality Standards - Image Requirements",
      },
    ],
  },
  statistics: {
    total_tables_checked: 59,
    tables_with_source_date: 45,
    total_charts_analyzed: 52,
    numerical_values_checked: 234,
    values_matching_reference: 198,
  },
}
