from typing import Any, List, Sequence

class Flowable: ...

class Paragraph(Flowable):
    def __init__(self, text: str, style: Any) -> None: ...

class Spacer(Paragraph):
    def __init__(self, width: float, height: float) -> None: ...

class Table(Paragraph):
    def __init__(self, data: List[List[Any]], colWidths: Any = ..., style: Any = ...) -> None: ...
    def setStyle(self, style: Any) -> None: ...

class TableStyle:
    def __init__(self, commands: List[Any]) -> None: ...

class SimpleDocTemplate:
    def __init__(self, filename: str, pagesize: Any = ..., **kwargs: Any) -> None: ...
    def build(self, flowables: Sequence[Flowable]) -> None: ...
